import test from 'node:test';
import assert from 'node:assert/strict';
import { ReactAdapter } from '../../src/adapter/react/ReactAdapter.js';
import { AttributionQuality, CapabilitySupport, EvidenceLevel, FrameworkCapability, RuntimeEventType } from '../../src/core/evidence-protocol.js';

class MockStore {
  constructor(){this.events=[];this.sequence=0;}
  emit(input){const e=Object.freeze({...input,id:input.id||`e${++this.sequence}`,sequence:this.sequence,timestamp:this.sequence,correlation:Object.freeze({traceId:null,interactionId:null,parentEventId:null,causedByEventId:null,...(input.correlation||{})}),evidence:Object.freeze({...input.evidence}),payload:Object.freeze({...input.payload}),owner:input.owner?Object.freeze({...input.owner}):null,framework:Object.freeze({...input.framework})});this.events.push(e);return e;}
}
const setup=()=>{const store=new MockStore();const adapter=new ReactAdapter({store,version:'19.x'});return{store,adapter,token:{}};};

test('capability honesty keeps update cause unsupported',()=>{const {adapter}=setup();assert.equal(adapter.capability(FrameworkCapability.UPDATE_CAUSE),CapabilitySupport.UNSUPPORTED);assert.equal(adapter.capability(FrameworkCapability.RESOURCE_OWNERSHIP),CapabilitySupport.PARTIAL);});
test('profiling flag strengthens only render timing capability',()=>{const a=new ReactAdapter({store:new MockStore(),profilingEnabled:true});assert.equal(a.capability(FrameworkCapability.RENDER_TIMING),CapabilitySupport.FRAMEWORK_REPORTED);assert.equal(a.capability(FrameworkCapability.UPDATE_CAUSE),CapabilitySupport.UNSUPPORTED);});
test('lifecycle generations isolate reconnects',()=>{const {adapter,token}=setup();const a=adapter.connect(token);adapter.disconnect(token);const b=adapter.connect(token);assert.equal(a.instanceId,b.instanceId);assert.notEqual(a.id,b.id);assert.equal(b.lifecycleGeneration,2);});
test('single pending request is structural parent only',()=>{const {adapter,token}=setup();adapter.connect(token);const r=adapter.recordUpdateRequested(token,{source:{file:'/src/A.jsx'}});const c=adapter.recordProfilerRender(token,{actualDuration:2});assert.equal(c.correlation.parentEventId,r.id);assert.equal(c.correlation.causedByEventId,null);});
test('multiple pending requests do not invent one parent',()=>{const {adapter,token}=setup();adapter.connect(token);adapter.recordUpdateRequested(token);adapter.recordUpdateRequested(token);const c=adapter.recordProfilerRender(token,{actualDuration:2});assert.equal(c.payload.pendingRequestCount,2);assert.equal(c.correlation.parentEventId,null);});
test('Profiler commit is framework-reported observation only',()=>{const {adapter,token}=setup();adapter.connect(token);const e=adapter.recordProfilerRender(token,{actualDuration:3});assert.equal(e.evidence.level,EvidenceLevel.OBSERVATION);assert.equal(e.evidence.attribution,AttributionQuality.FRAMEWORK_REPORTED);assert.equal(e.correlation.causedByEventId,null);});
test('state instrumentation is source-attributed only when source exists',()=>{const {adapter,token}=setup();adapter.connect(token);const a=adapter.recordStateChange(token,'q','a','b');const b=adapter.recordStateChange(token,'q','b','c',{source:{file:'/src/S.jsx'}});assert.equal(a.evidence.attribution,AttributionQuality.UNKNOWN);assert.equal(b.evidence.attribution,AttributionQuality.SOURCE_ATTRIBUTED);});
test('resource acquisition fails safe without source',()=>{const {adapter,token}=setup();adapter.connect(token);const a=adapter.recordResourceAcquired(token,{resourceId:'t1',resourceType:'interval'});const b=adapter.recordResourceAcquired(token,{resourceId:'t2',resourceType:'interval',source:{file:'/src/T.jsx'}});assert.equal(a.evidence.attribution,AttributionQuality.UNKNOWN);assert.equal(b.evidence.attribution,AttributionQuality.SOURCE_ATTRIBUTED);assert.notEqual(a.evidence.attribution,AttributionQuality.DETERMINISTIC);});
test('resource release remains recordable after disconnect',()=>{const {adapter,token}=setup();adapter.connect(token);adapter.recordResourceAcquired(token,{resourceId:'s'});adapter.disconnect(token);const r=adapter.recordResourceReleased(token,{resourceId:'s'});assert.equal(r.type,RuntimeEventType.RESOURCE_RELEASED);});
test('effect bridge is immutable and lower-certainty without source',()=>{const {adapter,token}=setup();adapter.connect(token);const b=adapter.createEffectBridge(token,'e');const s=b.start();const c=b.cleanup();assert.equal(Object.isFrozen(b),true);assert.equal(s.evidence.attribution,AttributionQuality.UNKNOWN);assert.equal(c.payload.diagnostic,'react.effect.cleanup');});
test('capability resolver caps React resource coverage',()=>{const {adapter}=setup();const r=adapter.createCapabilityResolver();assert.equal(r('react',FrameworkCapability.RESOURCE_OWNERSHIP),CapabilitySupport.PARTIAL);assert.equal(r('vue',FrameworkCapability.RESOURCE_OWNERSHIP),CapabilitySupport.UNSUPPORTED);});
test('Profiler callback isolates diagnostics failures',()=>{const adapter=new ReactAdapter({store:{emit(){throw new Error('x');}}});const cb=adapter.createProfilerCallback({});assert.doesNotThrow(()=>cb('id','update',1,1,1,2));assert.equal(cb('id','update',1,1,1,2),null);});
test('invalid disconnected tokens fail closed',()=>{const {adapter,token,store}=setup();assert.equal(adapter.connect(null),null);assert.equal(adapter.recordProfilerRender(token,{actualDuration:1}),null);assert.equal(store.events.length,0);});
test('duplicate connect is idempotent',()=>{const {adapter,token,store}=setup();const a=adapter.connect(token);const b=adapter.connect(token);assert.equal(a,b);assert.equal(store.events.filter(e=>e.type===RuntimeEventType.OWNER_CREATED).length,1);});
test('disconnect clears pending context before reconnect',()=>{const {adapter,token}=setup();adapter.connect(token);adapter.recordUpdateRequested(token);adapter.disconnect(token);adapter.connect(token);const c=adapter.recordProfilerRender(token,{actualDuration:1});assert.equal(c.payload.pendingRequestCount,0);});
test('diagnostics snapshot is structural and frozen',()=>{const {adapter,token}=setup();adapter.connect(token);adapter.recordUpdateRequested(token);const s=adapter.diagnosticsSnapshot(token);assert.equal(s.pendingUpdateRequests,1);assert.equal(Object.isFrozen(s),true);});
